"""Opt-in local tests. No copyrighted save or credential fixture is distributed.

Run with XSAVE_SAMPLE_ROOT pointing to a tree containing simu/ and 360original/.
All generated bytes and reports are kept beneath the project's ignored .local/.
"""
from hashlib import sha256
import json
import os
from pathlib import Path
import unittest
from importlib.util import find_spec
import tempfile
import zipfile

from xsave.adapters import adapt
from xsave.converter import to_xbox, to_xenia
from xsave.stfs import StfsPackage
from xsave.xenia import discover


@unittest.skipUnless(os.environ.get('XSAVE_SAMPLE_ROOT'), 'private samples supplied locally only')
class RealSampleTests(unittest.TestCase):
    def test_ngii_real_batch_round_trip(self):
        if not find_spec('cryptography'):
            self.skipTest('cryptography required to verify the native donor signature')
        from xsave.batch import convert_batch

        source = Path(os.environ['XSAVE_SAMPLE_ROOT']).absolute()
        project = Path(__file__).resolve().parents[1]
        runs = project / '.local' / 'ngii-batch'
        runs.mkdir(parents=True, exist_ok=True)
        run = Path(tempfile.mkdtemp(prefix='run-', dir=runs))
        originals = [p for tree in ('simu', '360original')
                     for p in (source / tree).rglob('*') if p.is_file()]
        before = {p: sha256(p.read_bytes()).hexdigest() for p in originals}
        saves = discover(source / 'simu')
        self.assertEqual(len(saves), 7)
        self.assertEqual({save.title_id for save in saves}, {0x544307D5})
        self.assertEqual({save.content_type for save in saves}, {1})
        self.assertEqual(len({save.package_name.casefold() for save in saves}), 7)

        donor = None
        for path in sorted((source / '360original').rglob('*')):
            if not path.is_file() or path.read_bytes()[:4] != b'CON ':
                continue
            package = StfsPackage(path.read_bytes())
            if (package.metadata.title_id == 0x544307D5
                    and package.metadata.content_type == 1
                    and package.validate()['signature'] == 'valid'):
                donor = path
                break
        self.assertIsNotNone(donor, 'No signed same-title CON Saved Game donor')
        profile = StfsPackage(donor.read_bytes()).metadata.profile_id
        xbox_root = run / 'xbox'
        xbox = convert_batch('to-xbox', source / 'simu', xbox_root,
                             template=donor, unsigned=True)
        self.assertEqual((xbox['status'], xbox['total'], xbox['succeeded'], xbox['failed']),
                         ('batch_complete', 7, 7, 0))
        self.assertEqual(len(xbox['results']), 7)
        for row in xbox['results']:
            report = row['report']
            original = next(save for save in saves if save.package_name == report['package'])
            output = (xbox_root / 'Content' / profile.hex().upper()
                      / '544307D5' / '00000001' / original.package_name)
            self.assertEqual(Path(report['output']), output)
            self.assertEqual(report['status'], 'unsigned_draft')
            converted = StfsPackage(output.read_bytes())
            expected = adapt(original.title_id, original.files, original.xuid,
                             int.from_bytes(profile, 'big')).files
            self.assertEqual(converted.files, expected)
            self.assertEqual(converted.metadata.title_id, 0x544307D5)
            self.assertEqual(converted.validate()['signature'], 'missing')
            self.assertTrue(converted.validate()['structural_valid'])
            with zipfile.ZipFile(report['backup']) as snapshot:
                self.assertIsNone(snapshot.testzip())

        system = next(save for save in saves if 'ng2sysd.dat' in save.files)
        original_system_xuid = int.from_bytes(system.files['ng2sysd.dat'][:8], 'big')
        xenia_root = run / 'xenia'
        exported = convert_batch('to-xenia', xbox_root, xenia_root,
                                 xuid=original_system_xuid)
        self.assertEqual((exported['status'], exported['total'],
                          exported['succeeded'], exported['failed']),
                         ('batch_complete', 7, 7, 0))
        self.assertEqual(len(exported['results']), 7)
        returned = {save.package_name: save for save in discover(xenia_root)}
        self.assertEqual(set(returned), {save.package_name for save in saves})
        for original in saves:
            result = returned[original.package_name]
            self.assertEqual(result.title_id, original.title_id)
            self.assertEqual(result.xuid, original_system_xuid)
            self.assertEqual(result.files, original.files)
        for row in exported['results']:
            with zipfile.ZipFile(row['report']['backup']) as snapshot:
                self.assertIsNone(snapshot.testzip())
        after = {p: sha256(p.read_bytes()).hexdigest() for p in originals}
        self.assertEqual(before, after)
        evidence = {'run': str(run), 'original_files_unchanged': len(originals),
                    'packages_round_tripped': len(saves),
                    'native_donor_sha256': before[donor],
                    'xbox_status': xbox['status'], 'xenia_status': exported['status'],
                    'retail_console_test': 'not_tested', 'xenia_runtime_test': 'not_tested'}
        (runs / 'ngii-batch-latest.json').write_text(json.dumps(evidence, indent=2), encoding='utf-8')

    def test_ngii_real_bidirectional(self):
        if not find_spec('cryptography'):
            self.skipTest('cryptography required to assert native content RSA signatures')
        source = Path(os.environ['XSAVE_SAMPLE_ROOT']).absolute()
        project = Path(__file__).resolve().parents[1]
        runs = project / '.local' / 'ngii'
        runs.mkdir(parents=True, exist_ok=True)
        import tempfile
        run = Path(tempfile.mkdtemp(prefix='run-', dir=runs))
        real_files = [p for tree in ('simu', '360original') for p in (source / tree).rglob('*') if p.is_file()]
        before = {p: sha256(p.read_bytes()).hexdigest() for p in real_files}
        donors = {}
        native_checks = []
        native_system_preserved = 0
        for path in (source / '360original').rglob('*'):
            if not path.is_file() or path.read_bytes()[:4] != b'CON ':
                continue
            package = StfsPackage(path.read_bytes())
            if package.metadata.title_id != 0x544307D5:
                continue
            validation = package.validate()
            self.assertEqual(validation['signature'], 'valid')
            native_checks.append(validation)
            donors[path.name] = path
            if 'ng2sysd.dat' in package.files:
                exported = run / 'native-system-export' / path.name
                native_report = to_xenia(path, exported)
                self.assertEqual(discover(exported)[0].files, package.files)
                self.assertFalse(native_report['file_provenance']['ng2sysd.dat']['changed'])
                preserved = run / 'native-system-preserved' / path.name
                preserved_report = to_xbox(exported, path, preserved)
                self.assertEqual(preserved_report['status'], 'preserved_donor_signature')
                self.assertEqual(preserved.read_bytes(), path.read_bytes())
                native_system_preserved += 1
        self.assertGreaterEqual(len(donors), 23)
        self.assertGreater(native_system_preserved, 0)
        saves = discover(source / 'simu')
        self.assertEqual(len(saves), 7)  # Actual payload packages, not 25 sidecars.
        reports = []
        for save in saves:
            folder = source / 'simu' / '544307D5' / '00000001' / save.package_name
            donor = donors.get(save.package_name)
            if donor is None:
                # Some emulator slots have no same-name donor. Select by actual
                # payload length/header; the generic writer uses source names.
                original = next(iter(save.files.values()))
                candidates = [path for path in donors.values()
                              if any(len(blob) == len(original) and blob[:32] == original[:32]
                                     for blob in StfsPackage(path.read_bytes()).files.values())]
                self.assertTrue(candidates, 'No structurally matching same-title template')
                donor = candidates[0]
            output = run / 'xbox' / save.package_name
            report = to_xbox(folder, donor, output, unsigned=True)
            native = StfsPackage(donor.read_bytes())
            expected = adapt(save.title_id, save.files, save.xuid,
                             int.from_bytes(native.metadata.profile_id, 'big')).files
            converted = StfsPackage(output.read_bytes())
            self.assertEqual(converted.files, expected)
            self.assertEqual(converted.metadata.title_id, 0x544307D5)
            self.assertEqual(converted.validate()['signature'], 'missing')
            self.assertNotEqual(converted.files, native.files)
            export = run / 'xenia' / save.package_name
            back_report = to_xenia(output, export)
            returned = discover(export)[0]
            self.assertEqual(returned.files, expected)
            # Reverse the known system XUID rebinding to establish payload provenance.
            original_system = next((b for n, b in save.files.items() if n == 'ng2sysd.dat'), None)
            if original_system is not None:
                original_xuid = int.from_bytes(original_system[:8], 'big')
                restored = adapt(save.title_id, returned.files, returned.xuid, original_xuid).files
                self.assertEqual(restored, save.files)
            reports.append({'to_xbox': report, 'to_xenia': back_report})
        after = {p: sha256(p.read_bytes()).hexdigest() for p in real_files}
        self.assertEqual(before, after)
        evidence = {'original_files_unchanged': len(before), 'native_packages_validated': len(native_checks),
                    'native_system_signature_round_trips': native_system_preserved,
                    'native_signature_results': [r['signature'] for r in native_checks],
                    'packages_round_tripped': len(reports), 'reports': reports,
                    'retail_console_test': 'not_tested', 'xenia_runtime_test': 'not_tested'}
        (run / 'validation.json').write_text(json.dumps(evidence, indent=2), encoding='utf-8')
        (project / '.local' / 'ngii-latest.json').write_text(
            json.dumps({'run': str(run), 'summary': {k: v for k, v in evidence.items() if k != 'reports'}}, indent=2),
            encoding='utf-8')

